cards_task/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('chat.urls')),
]

chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^registration/$', views.SignUpView.as_view(), name='registration'),
    url(r'^users/$', views.UserListView.as_view(), name='users'),
    url(r'^inbox/$', views.InboxView.as_view(), name='inbox'),
    url(r'^sent/$', views.SentView.as_view(), name='sent'),
    url(r'^letters/(?P<letter_id>\d+)/$', views.LetterDetailView.as_view(), name='letter'),
    url(r'^letters/new_letter/$', views.SendLetterView.as_view(), name='new_letter'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Letter(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    theme = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    letter_body = models.TextField()

    def get_absolute_url(self):
        return "/letters/%i/" % self.id

chat/forms.py
from .models import Letter
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LetterForm(ModelForm):
    class Meta:
        model = Letter
        exclude = ['pub_date', 'author']

    def __init__(self, *args, **kwargs):
        super(LetterForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserCreationFormWidget(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationFormWidget, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class AuthenticationFormWidget(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(AuthenticationFormWidget, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

chat/views.py
from django.contrib.auth import  login, logout
from django.contrib.auth.models import User
from django.views.generic import FormView, View, ListView
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404

from .models import Letter
from .forms import LetterForm, UserCreationFormWidget, AuthenticationFormWidget


def index_view(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect("/inbox/")
    return render(request, 'base_generic.html')


class LoginFormView(FormView):
    form_class = AuthenticationFormWidget
    template_name = "registration/login.html"
    success_url = "/inbox/"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")


class UserListView(ListView):
    model = User
    template_name = 'users.html'
    ordering = ['username']


class SignUpView(FormView):
    form_class = UserCreationFormWidget
    template_name = 'registration/signup.html'
    success_url = '/login/'

    def form_valid(self, form):
        form.save()
        return super(SignUpView, self).form_valid(form)


class InboxView(ListView):
    model = Letter
    template_name = 'inbox.html'
    context_object_name = 'letters'
    ordering = ['-pub_date']

    def get(self, request, *args, **kwargs):
        self.queryset = Letter.objects.filter(to__exact=request.user)
        return super(InboxView, self).get(request)


class SentView(ListView):
    model = Letter
    template_name = 'sent.html'
    context_object_name = 'letters'
    ordering = ['-pub_date']

    def get(self, request, *args, **kwargs):
        self.queryset = Letter.objects.filter(author__exact=request.user)
        return super(SentView, self).get(request)


class LetterDetailView(View):
    template_name = 'letter_detail.html'

    def get(self, request, letter_id, *args, **kwargs):
        letter = Letter.objects.get(id=letter_id)
        if request.user == letter.author or request.user == letter.to:
            return render(request, self.template_name, {'letter': letter})
        else:
            return Http404


class SendLetterView(FormView):
    form_class = LetterForm
    success_url = '/sent/'
    template_name = 'new_letter.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_letter = form.save(commit=False)
            new_letter.author = request.user
            new_letter.save()
            return HttpResponseRedirect(reverse("sent"))
        else:
            return render(request, self.template_name, {"form": form})

templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}<title>Главная</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}
        {% if user.is_authenticated %}
        {% else %}
            <h1 align=center>IChat</h1>
            <hr>
        {% endif %}

        <div align="center">
            <h3 style="color: #000080;">Кирилл и Арсений, добро пожаловать на мини-чат для обмена текстовыми сообщениями</h3>
        </div>
        <div align="center">
            <p>Если вы уже зарегистрированы на сайте, введите свой логин и пароль</p>
            <p><a href="{% url 'login' %}">Войти на сайт</a></p>
            <p>Вы также можете перейти на страницу регистрации</p>
            <p><a href="{% url 'registration' %}">Зарегистрироваться</a></p>
        </div>
        {% endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">IChat</a>
        </div>
    {% if user.is_authenticated %}<div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'inbox' %}">Входящие</a></li>
            <li><a href="{% url 'sent' %}">Отправленные</a></li>
            <li><a href="{% url 'new_letter' %}">Написать письмо</a></li>
            <li><a href="{% url 'users' %}">Пользователи сайта</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>Здравствуйте, {{ user.username }}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'logout' %}">Выход</a></li>
                </ul>
            </li>
        </ul>
    {% endif %}
    </div>
  </div>
</nav>

templates/inbox.html
{% extends "base_generic.html" %}
{% block title %}<title>Входящие</title>{% endblock %}

{% block content %}
    <h3 class="text-center">Входящие</h3>
    {% if letters %}
        <table class="table table-hover">
            <thead>
            <td>Тема сообщения</td>
            <td>Получено от</td>
            <td>Время получения</td>
            </thead>
    {% for letter in letters %}
            <tr>
                <td><a href="{{ letter.get_absolute_url }}">{{ letter.theme }}</a></td>
                <td>{{letter.author}}</td>
                <td>{{letter.pub_date}}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h4 class="text-center">У вас нет входящих писем :(</h4>

{% endif %}
{% endblock %}

templates/letter_detail.html
{% extends "base_generic.html" %}
{% block title %}<title>Письмо от {{letter.author}} к {{letter.to}}</title>{% endblock %}


{% block content %}
<h4>Письмо от {{letter.author}} к {{letter.to}}</h4>
    <ul>
        <li>
            От: {{letter.author}}
        </li>
        <li>
            Кому: {{letter.to}}
        </li>
        <li>
            Время получения: {{letter.pub_date}}
        </li>
        <li>
            Тема письма: {{letter.theme }}
        </li>
        <li>
            Содержание: <hr/>
            {{letter.letter_body}}
        </li>
    </ul>

{% endblock %}

templates/new_letter.html
{% extends "base_generic.html" %}
{% block title %}<title>Новое письмо</title>{% endblock %}

{% block content %}
<h3 class="text-center">Новое письмо</h3>
<div class="container">
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    <form class="form-group-sm" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div>
            <label for="id_to">Имя пользователя:</label>
            {{ form.to.errors }}
            {{ form.to}}
        </div>
        <div>
            <label for="id_theme">Тема сообщения:</label>
            {{ form.theme.errors }}
            {{ form.theme }}
        </div>
        <div>
            <label for="id_letter_body">Содержание сообщения:</label>
            {{ form.letter_body.errors }}
            {{ form.letter_body }}
        </div>
        <hr>
        <input class="btn btn-primary form-control" name="submit" type="submit" value="Отправить" />
    </form>
</div>
{% endblock %}

templates/sent.html
{% extends "base_generic.html" %}
{% block title %}<title>Исходящие</title>{% endblock %}

{% block content %}
    <h3 class="text-center">Отправленные</h3>
    {% if letters %}
    <table class="table table-hover">
        <thead>
            <td>Тема сообщения</td>
            <td>Отправлено</td>
            <td>Время отправления</td>
        </thead>

    {% for letter in letters %}
        <tr>
            <td><a href="{{ letter.get_absolute_url }}">{{ letter.theme }}</a></td>
            <td>{{letter.to}}</td>
            <td>{{letter.pub_date}}</td>
        </tr>
    {% endfor %}
    </table>
    {% else %}
        <h4 class="text-center">У вас нет отправленных писем. Напишите кому-нибудь! :)</h4>
    {% endif %}

{% endblock %}

templates/users.html
{% extends "base_generic.html" %}
{% block title %}<title>Пользователи</title>{% endblock %}

{% block content %}
    <h3 class="text-center">Все пользователи, зарегистрированные на сайте</h3>
    <p class="text-center">Вы сможете выбрать пользователя в форме отправки письма</p>
    <ul>
        {% for user in user_list %}
        <li>
            {{ user.username }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}